server.port=8080

spring.application.name=api-gateway

# --- Route: user-service ---
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=${USER_SERVICE_URL:http://user-service:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**

# --- Route: inventory-service ---
spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=${INVENTORY_SERVICE_URL:http://inventory-service:8082}
spring.cloud.gateway.routes[1].predicates[0]=Path=/inventory/**

# --- Route: order-service ---
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=${ORDER_SERVICE_URL:http://order-service:8083}
spring.cloud.gateway.routes[2].predicates[0]=Path=/order/**

management.endpoints.web.exposure.include=health,gateway
