spring.application.name=user-service

server.port=8081

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.pongs.user_service.model.entity
mybatis.configuration.map-underscore-to-camel-case=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration